;;; git-overleaf-command-test.el --- Command wrapper tests -*- lexical-binding: t; -*-

;; Copyright (C) 2026 Jamie Cui
;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Code:

(require 'cl-lib)
(require 'ert)
(require 'git-overleaf)

(defmacro git-overleaf-command-test--recording (&rest body)
  "Run BODY with command side effects recorded in `calls'."
  (declare (indent 0) (debug t))
  `(let ((calls nil))
     (cl-letf (((symbol-function 'git-overleaf--clone-sync)
                (lambda (&rest args)
                  (push (cons 'clone-sync args) calls)
                  'clone-result))
               ((symbol-function 'git-overleaf--clone-async)
                (lambda (&rest args)
                  (push (cons 'clone-async args) calls)
                  'clone-async-result))
               ((symbol-function 'git-overleaf--init-sync)
                (lambda (&rest args)
                  (push (cons 'init-sync args) calls)
                  'init-result))
               ((symbol-function 'git-overleaf--init-async)
                (lambda (&rest args)
                  (push (cons 'init-async args) calls)
                  'init-async-result))
               ((symbol-function 'git-overleaf--push-sync)
                (lambda (&rest args)
                  (push (cons 'push-sync args) calls)
                  'push-result))
               ((symbol-function 'git-overleaf--push-async)
                (lambda (&rest args)
                  (push (cons 'push-async args) calls)
                  'push-async-result))
               ((symbol-function 'git-overleaf--overwrite-remote-sync)
                (lambda (&rest args)
                  (push (cons 'overwrite-sync args) calls)
                  'overwrite-result))
               ((symbol-function 'git-overleaf--overwrite-remote-async)
                (lambda (&rest args)
                  (push (cons 'overwrite-async args) calls)
                  'overwrite-async-result))
               ((symbol-function 'git-overleaf--pull-sync)
                (lambda (&rest args)
                  (push (cons 'pull-sync args) calls)
                  'pull-result))
               ((symbol-function 'git-overleaf--pull-async)
                (lambda (&rest args)
                  (push (cons 'pull-async args) calls)
                  'pull-async-result))
               ((symbol-function 'git-overleaf--require-managed-repo)
                (lambda (&optional directory)
                  (push (list 'require-managed-repo directory) calls)
                  "/repo"))
               ((symbol-function 'git-overleaf-root)
                (lambda (&optional directory)
                  (push (list 'root directory) calls)
                  (and (not (equal directory "/missing"))
                       "/repo")))
               ((symbol-function 'git-overleaf--managed-repo-p)
                (lambda (repo)
                  (push (list 'managed-p repo) calls)
                  (equal repo "/repo")))
               ((symbol-function 'git-overleaf--warn)
                (lambda (&rest args)
                  (push (cons 'warn args) calls)))
               ((symbol-function 'git-overleaf--log-context-for-repo)
                (lambda (&optional repo)
                  (push (list 'log-context repo) calls)
                  nil)))
       ,@body)))

(ert-deftest git-overleaf-command-test-public-commands-dispatch-sync ()
  (git-overleaf-command-test--recording
    (should (eq (git-overleaf-clone "https://example.test" "/target")
                'clone-result))
    (should (eq (git-overleaf-init "/repo" "https://example.test")
                'init-result))
    (should (eq (git-overleaf-push "/repo")
                'push-result))
    (should (eq (git-overleaf-overwrite-remote "/repo")
                'overwrite-result))
    (should (eq (git-overleaf-pull "/repo")
                'pull-result))
    (should (equal (nreverse calls)
                   '((clone-sync "https://example.test" "/target")
                     (init-sync "/repo" "https://example.test" nil)
                     (root "/repo")
                     (managed-p "/repo")
                     (push-sync "/repo")
                     (require-managed-repo "/repo")
                     (overwrite-sync "/repo" nil nil)
                     (require-managed-repo "/repo")
                     (pull-sync "/repo" nil))))))

(ert-deftest git-overleaf-command-test-push-noerror-non-managed-repo ()
  (git-overleaf-command-test--recording
    (cl-letf (((symbol-function 'git-overleaf--managed-repo-p)
               (lambda (_repo) nil)))
      (should-not (git-overleaf-push "/repo" t)))
    (should (equal (nreverse calls)
                   '((root "/repo"))))))

(ert-deftest git-overleaf-command-test-push-errors-for-non-managed-repo ()
  (git-overleaf-command-test--recording
    (cl-letf (((symbol-function 'git-overleaf--managed-repo-p)
               (lambda (_repo) nil)))
      (should-error (git-overleaf-push "/missing")
                    :type 'user-error))))

(ert-deftest git-overleaf-command-test-push-noerror-demotes-sync-error ()
  (git-overleaf-command-test--recording
    (cl-letf (((symbol-function 'git-overleaf--push-sync)
               (lambda (&rest _args)
                 (error "push failed"))))
      (git-overleaf-push "/repo" t))
    (should (member
             '(warn "Automatic Overleaf push failed for %s: %s"
                    "/repo"
                    "push failed")
             calls))))

(ert-deftest git-overleaf-command-test-browse-remote-from-repo ()
  (let ((opened nil))
    (cl-letf (((symbol-function 'git-overleaf-root)
               (lambda (&optional _directory) "/repo"))
              ((symbol-function 'git-overleaf--set-repo-url)
               (lambda (&rest _args) nil))
              ((symbol-function 'git-overleaf--project-id)
               (lambda (_repo) "project-id"))
              ((symbol-function 'browse-url)
               (lambda (url &rest _args)
                 (setq opened url))))
      (let ((git-overleaf-url "https://example.overleaf.test"))
        (git-overleaf-browse-remote "/repo")
        (should (equal opened
                       "https://example.overleaf.test/project/project-id"))))))

(ert-deftest git-overleaf-command-test-overwrite-pending-confirmation ()
  (let ((prompt nil))
    (cl-letf (((symbol-function 'git-overleaf--pending-state)
               (lambda (_repo) '(:action pull)))
              ((symbol-function 'git-overleaf--project-name)
               (lambda (_repo) "Project"))
              ((symbol-function 'yes-or-no-p)
               (lambda (text)
                 (setq prompt text)
                 t)))
      (git-overleaf--confirm-overwrite-remote "/repo")
      (should (string-match-p "Abandon pending Overleaf pull" prompt)))))

(ert-deftest git-overleaf-command-test-overwrite-sync-interactive-confirms ()
  (let ((confirmed nil)
        (synced nil)
        (git-overleaf-enable-async nil))
    (cl-letf (((symbol-function 'git-overleaf--require-managed-repo)
               (lambda (&optional _directory) "/repo"))
              ((symbol-function 'called-interactively-p)
               (lambda (&optional _kind) t))
              ((symbol-function 'git-overleaf--confirm-overwrite-remote)
               (lambda (_repo)
                 (setq confirmed t)))
              ((symbol-function 'git-overleaf--overwrite-remote-sync)
               (lambda (&rest _args)
                 (setq synced t))))
      (call-interactively #'git-overleaf-overwrite-remote)
      (should confirmed)
      (should synced))))

(ert-deftest git-overleaf-command-test-overwrite-clears-pending-after-success ()
  (let ((calls nil))
    (cl-letf (((symbol-function 'git-overleaf--log-context-for-repo)
               (lambda (&rest _args) nil))
              ((symbol-function 'git-overleaf--ensure-no-pending-action)
               (lambda (&rest _args)
                 (ert-fail "overwrite must not reject pending state")))
              ((symbol-function 'git-overleaf--overwrite-pending-state)
               (lambda (_repo) '(:action pull)))
              ((symbol-function 'git-overleaf--set-repo-url)
               (lambda (&rest _args) nil))
              ((symbol-function 'git-overleaf--prepare-sync-metadata-repo)
               (lambda (&rest _args) nil))
              ((symbol-function 'git-overleaf--project-id)
               (lambda (_repo) "project-id"))
              ((symbol-function 'git-overleaf--prepare-working-tree-for-sync)
               (lambda (&rest _args) nil))
              ((symbol-function 'git-overleaf--with-remote-state)
               (lambda (_project-id function)
                 (funcall function "/remote" 'remote-table)))
              ((symbol-function 'git-overleaf--read-sync-state)
               (lambda (&rest _args)
                 '(:status diverged :head "head")))
              ((symbol-function 'git-overleaf--project-name)
               (lambda (_repo) "Project"))
              ((symbol-function 'git-overleaf--upload-head-and-set-base)
               (lambda (&rest _args)
                 (push 'upload calls)
                 'uploaded))
              ((symbol-function 'git-overleaf--clear-pending-state)
               (lambda (_repo)
                 (push 'clear calls))))
      (should (eq (git-overleaf--overwrite-remote-sync
                   "/repo" 'error t)
                  'uploaded))
      (should (equal (nreverse calls) '(upload clear))))))

(ert-deftest git-overleaf-command-test-overwrite-keeps-pending-after-failure ()
  (let ((cleared nil))
    (cl-letf (((symbol-function 'git-overleaf--log-context-for-repo)
               (lambda (&rest _args) nil))
              ((symbol-function 'git-overleaf--overwrite-pending-state)
               (lambda (_repo) '(:action pull)))
              ((symbol-function 'git-overleaf--set-repo-url)
               (lambda (&rest _args) nil))
              ((symbol-function 'git-overleaf--prepare-sync-metadata-repo)
               (lambda (&rest _args) nil))
              ((symbol-function 'git-overleaf--project-id)
               (lambda (_repo) "project-id"))
              ((symbol-function 'git-overleaf--prepare-working-tree-for-sync)
               (lambda (&rest _args) nil))
              ((symbol-function 'git-overleaf--with-remote-state)
               (lambda (_project-id function)
                 (funcall function "/remote" 'remote-table)))
              ((symbol-function 'git-overleaf--read-sync-state)
               (lambda (&rest _args)
                 '(:status diverged :head "head")))
              ((symbol-function 'git-overleaf--project-name)
               (lambda (_repo) "Project"))
              ((symbol-function 'git-overleaf--upload-head-and-set-base)
               (lambda (&rest _args)
                 (error "upload failed")))
              ((symbol-function 'git-overleaf--clear-pending-state)
               (lambda (_repo)
                 (setq cleared t))))
      (should-error
       (git-overleaf--overwrite-remote-sync "/repo" 'error t))
      (should-not cleared))))

(ert-deftest git-overleaf-command-test-overwrite-still-rejects-conflicts ()
  (let ((remote-read nil)
        (cleared nil))
    (cl-letf (((symbol-function 'git-overleaf--log-context-for-repo)
               (lambda (&rest _args) nil))
              ((symbol-function 'git-overleaf--overwrite-pending-state)
               (lambda (_repo) '(:action pull)))
              ((symbol-function 'git-overleaf--set-repo-url)
               (lambda (&rest _args) nil))
              ((symbol-function 'git-overleaf--prepare-sync-metadata-repo)
               (lambda (&rest _args) nil))
              ((symbol-function 'git-overleaf--project-id)
               (lambda (_repo) "project-id"))
              ((symbol-function 'git-overleaf--prepare-working-tree-for-sync)
               (lambda (&rest _args)
                 (user-error "unresolved merge conflicts")))
              ((symbol-function 'git-overleaf--with-remote-state)
               (lambda (&rest _args)
                 (setq remote-read t)))
              ((symbol-function 'git-overleaf--clear-pending-state)
               (lambda (_repo)
                 (setq cleared t))))
      (should-error
       (git-overleaf--overwrite-remote-sync "/repo" 'error t)
       :type 'user-error)
      (should-not remote-read)
      (should-not cleared))))

(ert-deftest git-overleaf-command-test-overwrite-async-allows-pending ()
  (let ((scheduled nil))
    (cl-letf (((symbol-function 'git-overleaf--log-context-for-repo)
               (lambda (&rest _args) nil))
              ((symbol-function 'git-overleaf--ensure-no-pending-action)
               (lambda (&rest _args)
                 (ert-fail "overwrite must not reject pending state")))
              ((symbol-function 'git-overleaf--set-repo-url)
               (lambda (&rest _args) nil))
              ((symbol-function 'git-overleaf--confirm-overwrite-remote)
               (lambda (_repo) nil))
              ((symbol-function 'git-overleaf--push-unstaged-action)
               (lambda (&rest _args) 'error))
              ((symbol-function 'git-overleaf--project-name)
               (lambda (_repo) "Project"))
              ((symbol-function 'git-overleaf--ensure-authenticated-async)
               (lambda (_description continuation)
                 (funcall continuation)))
              ((symbol-function 'git-overleaf--async-start)
               (lambda (&rest _args)
                 (setq scheduled t))))
      (git-overleaf--overwrite-remote-async "/repo")
      (should scheduled))))

(ert-deftest git-overleaf-command-test-pending-pull-error-is-actionable ()
  (cl-letf (((symbol-function 'git-overleaf--merge-in-progress-p)
             (lambda (_repo) nil))
            ((symbol-function 'git-overleaf--read-repo-status)
             (lambda (_repo)
               (make-git-overleaf--repo-status))))
    (let ((err (should-error (git-overleaf--signal-pending-pull "/repo")
                             :type 'user-error)))
      (should (string-match-p "/repo" (error-message-string err)))
      (should (string-match-p "no Git merge is active"
                              (error-message-string err)))
      (should (string-match-p "git-overleaf-push"
                              (error-message-string err)))
      (should (string-match-p "git-overleaf-overwrite-remote"
                              (error-message-string err))))))

(ert-deftest git-overleaf-command-test-overwrite-rejects-unknown-pending-action ()
  (cl-letf (((symbol-function 'git-overleaf--pending-state)
             (lambda (_repo) '(:action future-action))))
    (should-error (git-overleaf--overwrite-pending-state "/repo")
                  :type 'user-error)))

(ert-deftest git-overleaf-command-test-force-stop-delegates ()
  (let ((called nil))
    (cl-letf (((symbol-function 'git-overleaf--force-stop)
               (lambda () (setq called t))))
      (git-overleaf-force-stop)
      (should called))))

;;; git-overleaf-command-test.el ends here
