;;; git-overleaf-command-test.el --- Command wrapper tests -*- lexical-binding: t; -*-

;; Copyright (C) 2026 Jamie Cui
;; SPDX-License-Identifier: GPL-3.0-or-later

;;; Code:

(require 'cl-lib)
(require 'ert)
(require 'git-overleaf)

(defmacro git-overleaf-command-test--recording (&rest body)
  "Run BODY with command side effects recorded in `calls'."
  (declare (indent 0) (debug t))
  `(let ((calls nil))
     (cl-letf (((symbol-function 'git-overleaf--clone-sync)
                (lambda (&rest args)
                  (push (cons 'clone-sync args) calls)
                  'clone-result))
               ((symbol-function 'git-overleaf--init-sync)
                (lambda (&rest args)
                  (push (cons 'init-sync args) calls)
                  'init-result))
               ((symbol-function 'git-overleaf--push-sync)
                (lambda (&rest args)
                  (push (cons 'push-sync args) calls)
                  'push-result))
               ((symbol-function 'git-overleaf--reset-to-remote)
                (lambda (&rest args)
                  (push (cons 'reset args) calls)
                  'reset-result))
               ((symbol-function 'git-overleaf--abort-pending-pull)
                (lambda (&rest args)
                  (push (cons 'pull-abort args) calls)
                  'abort-result))
               ((symbol-function 'git-overleaf--pull-sync)
                (lambda (&rest args)
                  (push (cons 'pull-sync args) calls)
                  'pull-result))
               ((symbol-function 'git-overleaf--status-data)
                (lambda (&rest args)
                  (push (cons 'status args) calls)
                  '(:state in-sync)))
               ((symbol-function 'git-overleaf--require-managed-repo)
                (lambda (&optional directory)
                  (push (list 'require-managed-repo directory) calls)
                  "/repo"))
               ((symbol-function 'git-overleaf-root)
                (lambda (&optional directory)
                  (push (list 'root directory) calls)
                  (and (not (equal directory "/missing")) "/repo")))
               ((symbol-function 'git-overleaf--managed-repo-p)
                (lambda (repo)
                  (push (list 'managed-p repo) calls)
                  (equal repo "/repo")))
               ((symbol-function 'git-overleaf--notify-operation-succeeded)
                (lambda (&rest args)
                  (push (cons 'notify args) calls)))
               ((symbol-function 'git-overleaf--warn)
                (lambda (&rest args)
                  (push (cons 'warn args) calls)))
               ((symbol-function 'git-overleaf--log-context-for-repo)
                (lambda (&optional _repo) nil)))
       ,@body)))

(ert-deftest git-overleaf-command-test-public-commands-dispatch-sync ()
  (git-overleaf-command-test--recording
    (should (eq (git-overleaf-clone "https://example.test" "/target")
                'clone-result))
    (should (eq (git-overleaf-init "/repo" "https://example.test")
                'init-result))
    (should (eq (git-overleaf-push "/repo") 'push-result))
    (should (eq (git-overleaf-push "/repo" t) 'push-result))
    (should (eq (git-overleaf-reset "/repo" 'hard) 'reset-result))
    (should (eq (git-overleaf-pull-abort "/repo") 'abort-result))
    (should (eq (git-overleaf-pull "/repo") 'pull-result))
    (should (equal (git-overleaf-status "/repo") '(:state in-sync)))
    (dolist (call '((push-sync "/repo" nil)
                    (push-sync "/repo" t)
                    (reset "/repo" hard)
                    (pull-abort "/repo")
                    (pull-sync "/repo" nil)
                    (status "/repo")))
      (should (member call calls)))))

(ert-deftest git-overleaf-command-test-push-noerror-non-managed-repo ()
  (git-overleaf-command-test--recording
    (cl-letf (((symbol-function 'git-overleaf--managed-repo-p)
               (lambda (_repo) nil)))
      (should-not (git-overleaf-push "/repo" nil t)))
    (should (equal (nreverse calls) '((root "/repo"))))))

(ert-deftest git-overleaf-command-test-push-errors-for-non-managed-repo ()
  (git-overleaf-command-test--recording
    (cl-letf (((symbol-function 'git-overleaf--managed-repo-p)
               (lambda (_repo) nil)))
      (should-error (git-overleaf-push "/missing") :type 'user-error))))

(ert-deftest git-overleaf-command-test-push-noerror-demotes-sync-error ()
  (git-overleaf-command-test--recording
    (cl-letf (((symbol-function 'git-overleaf--push-sync)
               (lambda (&rest _args) (error "push failed"))))
      (git-overleaf-push "/repo" nil t))
    (should (member '(warn "Automatic Overleaf push failed for %s: %s"
                           "/repo" "push failed")
                    calls))))

(ert-deftest git-overleaf-command-test-force-push-confirms-interactively ()
  (let ((confirmed nil)
        (force nil)
        (git-overleaf-enable-async nil))
    (cl-letf (((symbol-function 'git-overleaf-root)
               (lambda (&optional _directory) "/repo"))
              ((symbol-function 'called-interactively-p)
               (lambda (&optional _kind) t))
              ((symbol-function 'git-overleaf--managed-repo-p)
               (lambda (_repo) t))
              ((symbol-function 'git-overleaf--project-name)
               (lambda (_repo) "Project"))
              ((symbol-function 'yes-or-no-p)
               (lambda (_prompt) (setq confirmed t)))
              ((symbol-function 'git-overleaf--push-sync)
               (lambda (_repo force-arg &optional _skip-auth)
                 (setq force force-arg))))
      (git-overleaf-push nil t nil)
      (should confirmed)
      (should force))))

(ert-deftest git-overleaf-command-test-force-push-rejection-stops-dispatch ()
  (cl-letf (((symbol-function 'git-overleaf--project-name)
             (lambda (_repo) "Project"))
            ((symbol-function 'yes-or-no-p) (lambda (_prompt) nil)))
    (should-error (git-overleaf--confirm-force-push "/repo")
                  :type 'user-error)))

(ert-deftest git-overleaf-command-test-reset-prefix-selects-hard ()
  (let ((mode nil)
        (current-prefix-arg '(4)))
    (cl-letf (((symbol-function 'git-overleaf--require-managed-repo)
               (lambda (&optional _directory) "/repo"))
              ((symbol-function 'git-overleaf--current-branch)
               (lambda (_repo) "main"))
              ((symbol-function 'yes-or-no-p) (lambda (_prompt) t))
              ((symbol-function 'git-overleaf--reset-to-remote)
               (lambda (_repo selected) (setq mode selected)))
              ((symbol-function 'git-overleaf--notify-operation-succeeded)
               #'ignore))
      (call-interactively #'git-overleaf-reset)
      (should (eq mode 'hard)))))

(ert-deftest git-overleaf-command-test-browse-remote-from-repo ()
  (let ((opened nil))
    (cl-letf (((symbol-function 'git-overleaf-root)
               (lambda (&optional _directory) "/repo"))
              ((symbol-function 'git-overleaf--set-repo-url) #'ignore)
              ((symbol-function 'git-overleaf--project-id)
               (lambda (_repo) "project-id"))
              ((symbol-function 'browse-url)
               (lambda (url &rest _args) (setq opened url))))
      (let ((git-overleaf-url "https://example.overleaf.test"))
        (git-overleaf-browse-remote "/repo")
        (should (equal opened
                       "https://example.overleaf.test/project/project-id"))))))

(ert-deftest git-overleaf-command-test-force-stop-delegates ()
  (let ((called nil))
    (cl-letf (((symbol-function 'git-overleaf--force-stop)
               (lambda () (setq called t))))
      (git-overleaf-force-stop)
      (should called))))

;;; git-overleaf-command-test.el ends here
